### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by erikronstrom** [EuAndreh/defclass-std#5]
The documentation says that:

```
(defclass/std example ()
  ((slot1 :with)
   (slot2)))
```

expands to

```
(DEFCLASS WITH ()
  ((SLOT1 :ACCESSOR EXAMPLE-SLOT1 :INITARG :SLOT1 :INITFORM NIL)
   (SLOT2 :ACCESSOR SLOT2 :INITARG :SLOT2 :INITFORM NIL)))
```

But the class name is wrong, it should really be

```
(DEFCLASS EXAMPLE ()
  ((SLOT1 :ACCESSOR EXAMPLE-SLOT1 :INITARG :SLOT1 :INITFORM NIL)
   (SLOT2 :ACCESSOR SLOT2 :INITARG :SLOT2 :INITFORM NIL)))
```

**Comment by EuAndreh** [comment]
Hi!

Erik Ronström <notifications@github.com> writes:

> The documentation says that:
>
> ```
> (defclass/std example ()
>   ((slot1 :with)
>    (slot2)))
> ```
>
> expands to
>
> ```
> (DEFCLASS WITH ()
>   ((SLOT1 :ACCESSOR EXAMPLE-SLOT1 :INITARG :SLOT1 :INITFORM NIL)
>    (SLOT2 :ACCESSOR SLOT2 :INITARG :SLOT2 :INITFORM NIL)))
> ```
>
> But the class name is wrong, it should really be
>
> ```
> (DEFCLASS EXAMPLE ()
>   ((SLOT1 :ACCESSOR EXAMPLE-SLOT1 :INITARG :SLOT1 :INITFORM NIL)
>    (SLOT2 :ACCESSOR SLOT2 :INITARG :SLOT2 :INITFORM NIL)))
> ```

Thanks for the report.

Fixed in 0300f171c1308e5ff3efd66b4f4e766f2bcde259.
